/*
 * generated by Xtext 2.29.0
 */
package edu.kit.archicorc2.edl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEventsValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.kit.archicorc2.edl.events.EventsPackage.eINSTANCE);
		return result;
	}
}
