/**
 * generated by Xtext 2.29.0
 */
package tu_bs.cs.isf.mapping.mapping;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Author</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tu_bs.cs.isf.mapping.mapping.MappingPackage#getAuthor()
 * @model
 * @generated
 */
public interface Author extends Annotation
{
} // Author
