/*
 * generated by Xtext 2.29.0
 */
package edu.kit.archicorc2.edl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEventsScopeProvider extends DelegatingScopeProvider {
}
