/*
 * generated by Xtext 2.20.0
 */
package edu.kit.archicorc2.edl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.kit.archicorc2.edl.EventsRuntimeModule;
import edu.kit.archicorc2.edl.EventsStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EventsIdeSetup extends EventsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EventsRuntimeModule(), new EventsIdeModule()));
	}
	
}
