/*
 * generated by Xtext 2.29.0
 */
package edu.kit.archicorc2.edl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EventsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/kit/archicorc2/edl/parser/antlr/internal/InternalEvents.tokens");
	}
}
