/*
 * generated by Xtext 2.29.0
 */
package edu.kit.archicorc2.edl.ui.tests;

import com.google.inject.Injector;
import edu.kit.archicorc2.edl.ui.internal.EdlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EventsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EdlActivator.getInstance().getInjector("edu.kit.archicorc2.edl.Events");
	}

}
