/*
 * generated by Xtext 2.20.0
 */
package edu.kit.archicorc2.edl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EventsStandaloneSetup extends EventsStandaloneSetupGenerated {

	public static void doSetup() {
		new EventsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
