/*
 * generated by Xtext 2.15.0
 */
package edu.kit.archicorc2.idl.ide

import com.google.inject.Guice
import edu.kit.archicorc2.idl.CidlRuntimeModule
import edu.kit.archicorc2.idl.CidlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CidlIdeSetup extends CidlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CidlRuntimeModule, new CidlIdeModule))
	}
	
}
