/*
 * generated by Xtext 2.29.0
 */
package edu.kit.archicorc2.edl.ui;

import com.google.inject.Injector;
import edu.kit.archicorc2.edl.ui.internal.EdlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EventsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EdlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EdlActivator activator = EdlActivator.getInstance();
		return activator != null ? activator.getInjector(EdlActivator.EDU_KIT_ARCHICORC2_EDL_EVENTS) : null;
	}

}
